//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxToLux.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_VRENDTITLE                  2
#define IDS_OPTIONS                     3
#define IDS_WRITE_FILE                  4
#define IDS_REND_FILE_OVERWRITE         5
#define IDS_DENOISER                    5
#define IDS_RENDER_TYPE_PATHCPU         6
#define IDS_RENDER_ERR                  7
#define IDS_CANT_OPEN                   8
#define IDS_FILTER                      9
#define IDS_AUTOLINEAR                  9
#define IDS_FILE                        10
#define IDS_FILE_ALREADY_EXISTS         11
#define IDD_DEPTH                       12
#define IDS_POSTPROCCESS                12
#define IDS_RENDER_TYPE                 13
#define IDS_SAMPLER                     14
#define IDS_FILTERS                     15
#define IDS_DEPTH                       16
#define IDS_CLASS_NULL                  17
#define IDD_DIALOG1                     18
#define IDS_EMISSION                    18
#define IDD_RENDER_PARAMS               19
#define IDS_EMISSION_MAP                19
#define IDD_RENDER_PROG                 20
#define IDS_EMISSION_POWER              20
#define IDD_RENDER_SAMPLER              21
#define IDS_EMISSION_EFFICENCY          21
#define IDD_RENDER_FILTER               22
#define IDS_EMISSION_MAPFILE            22
#define IDD_RENDER_SAMPLER1             23
#define IDS_EMISSION_GAMMA              23
#define IDC_FILE                        24
#define IDS_EMISSION_IESFILE            24
#define IDC_FILENAME                    25
#define IDS_EMISSION_FLIPZ              25
#define IDC_COMBO1                      26
#define IDS_EMISSION_SAMPLES            26
#define IDC_BUTTON1                     27
#define IDS_EMISSION_MAP_WIDTH          27
#define IDC_COMBO2                      28
#define IDS_EMISSION_MAP_HEIGHT         28
#define IDC_SAMPLER_TYPE_COMBO          29
#define IDS_EMISSION_ID                 29
#define IDC_ENABLEEMISSION              29
#define IDC_COMBO_FILM_OUTPUT_TYPE      30
#define IDS_ENABLEEMISSION              30
#define IDC_HALTTIME                    31
#define IDS_POSTPROCCESS_FILTERS        31
#define IDS_POSTPROCCESS_EFFECTS        31
#define IDC_CHECK_OPENCL_CPU            32
#define IDC_CHECK_OPENCL_DEVICE1        32
#define IDS_ENVIRENMENT_MAP             32
#define IDC_CHECK_OPENCL_GPU            33
#define IDC_CHECK_OPENCL_DEVICE2        33
#define IDS_DB_NONE                     33
#define IDC_FILENAME2                   34
#define IDC_HALTTIME2                   34
#define IDS_BUMP_MAP                    34
#define IDC_CHECK_OPENCL_DEVICE4        34
#define IDC_COMBO_FILM_OUTPUT_TYPE2     35
#define IDS_AMOUNT_MAP                  35
#define IDC_CHECK_OPENCL_GPU3           35
#define IDC_CHECK_OPENCL_DEVICE3        35
#define IDC_COMBO_RENDERTYPE_NEW        36
#define IDS_NORMAL_MAP                  36
#define IDC_CHECK_OPENCL_GPU2           36
#define IDC_HALTTIME3                   36
#define IDC_CHECK_OPENCL_DEVICE5        36
#define IDC_RENDERTYPE_NEW              37
#define IDS_INTERIOR_MAP                37
#define IDC_CHECK_DEFAULT_LIGHT         38
#define IDS_EXTERIOR_MAP                38
#define IDC_CHECK_DEFUALT_LIGHT_DISABLE 39
#define IDS_BUMP_SAMPLE                 39
#define IDC_CUSTOM1                     40
#define IDS_MATERIAL_ID                 40
#define IDC_ANGLE                       41
#define IDS_TRANSPARENCY                41
#define IDC_OUTPUTSCENE                 42
#define IDS_RENDER_TIMER                42
#define IDC_SOBOL_Depth2                43
#define IDS_LIGHT_PATH                  43
#define IDS_LIGHT_PATHS                 43
#define IDC_FILTER_GUASSIAN_ALPHA       44
#define IDS_ABOUT_LUX                   44
#define IDC_OUTPUTSCENE_NEW             45
#define IDC_RENDERTYPE                  46
#define IDC_FILTERYWIDTH_SPIN2          47
#define IDC_FILTER_GUASSIAN_ALPHA_SPIN  48
#define IDC_COMBO_LIGHT_STRATEGY        49
#define IDC_SOBOL_Depth3                50
#define IDC_CHECK_OVERRIDE_MATTERIALS   51
#define IDC_SOBOL_Depth4                52
#define IDC_CUSTOM2                     53
#define IDC_SOBOL_Depth5                54
#define IDC_ANGLESPIN                   55
#define IDC_SOBOL_Depth6                56
#define IDC_LENSRADIUS_SPIN             57
#define IDC_VBINTERVAL                  58
#define IDC_FILTERS_TYPE_COMBO          59
#define IDC_FILTERYWIDTH                60
#define IDC_CHECK1                      61
#define IDC_SOBOL_Depth                 62
#define IDC_FILTERYWIDTH_SPIN           63
#define IDC_CAMERA_BLUR                 64
#define IDC_CAMERA_DEPTH                65
#define IDC_FILTERXWIDTH                66
#define IDC_FILTERXWIDTH_SPIN           67
#define IDC_FILTER_MITCHEL_A_FLOAT      68
#define IDC_FILTER_MITCHEL_A_FLOAT_SPIN 69
#define IDC_FILTER_MITCHEL_B_FLOAT      70
#define IDC_FILTER_MITCHEL_B_FLOAT_SPIN 71
#define IDC_STATIC_FILTER_X_WIDTH_LABEL 72
#define IDC_STATIC_FILTER_Y_WIDTH_LABEL 73
#define IDC_STATIC_FILTER_GUASSIAN_FILTER_ALPHA 74
#define IDC_STATIC_FILTER_REC_RANGE1    75
#define IDC_STATIC_FILTER_REC_RANGE2    76
#define IDC_STATIC_FILTER_REC_GUASSIAN_RANGE 77
#define IDC_STATIC_MITCHEL_FRAME        78
#define IDC_STATIC_FILTER_MITCHELL_A_LABEL 79
#define IDC_STATIC_FILTER_MITCHELL_A_RANGE 80
#define IDC_STATIC_FILTER_MITCHELL_B_LABEL 81
#define IDC_STATIC_FILTER_MITCHELL_B_RANGE 82
#define IDC_IMAGE_MUTATION_RATE_NEW     83
#define IDC_METROPOLIS_LARGEST_EP_RATE_SPIN_NEW 84
#define IDC_MAX_CONSECUTIVE_REJECT_SPIN_NEW 85
#define IDC_MAX_CONSECUTIVE_SPIN        85
#define IDC_IMAGE_MUTATION_RATE_SPIN_NEW 86
#define IDC_METROPOLIS_LARGEST_EP_RATE_NEW 87
#define IDC_MAX_CONSECUTIVE_REJECT_NEW  88
#define IDC_MAX_CONSECUTIVE             88
#define IDC_METROPOLIS_LABEL1           89
#define IDC_METROPOLIS_LABEL2           90
#define IDC_RENDERTYPE_OLD              91
#define IDC_METROPOLIS_LABEL3           92
#define IDC_LENSRADIUS                  93
#define IDS_CATEGORY                    94
#define IDS_SHADERS_CATEGORY            94
#define IDS_PARAMS                      95
#define IDS_NULL_PARAMS                 95
#define IDS_CLASS_LUXCORE               96
#define IDD_NULL_PANEL                  101
#define IDS_FILESAVER                   102
#define IDS_BASICS                      103
#define IDD_LIGHT_PANEL                 106
#define IDS_LIGHT_PARAMS                107
#define IDD_RENDER_FILE                 109
#define IDD_GAMMA                       110
#define IDD_POSTPROCCESS                110
#define IDS_GAMMA                       111
#define IDD_POSTPROCCESS_EFFECTS        112
#define IDD_ENVIRENMENT_PANEL           113
#define IDD_LIGHT_PATHS                 114
#define IDD_ABOUT                       115
#define IDB_LUX_LOGO                    121
#define IDC_EMISSION_POWER              1015
#define IDC_EMISSION_POWER_SPIN         1016
#define IDC_EMISSION_EFFICENCY          1017
#define IDC_EMISSION_EFFICENCY_SPIN     1018
#define IDC_EMISSION_GAMMA              1019
#define IDC_EMISSION_GAMMA_SPIN         1020
#define IDC_EMISSION_SAMPLES            1021
#define IDC_EMISSION_SAMPLES_SPIN       1022
#define IDC_EMISSION_MAP_WIDTH          1023
#define IDC_EMISSION_MAP_WIDTH_SPIN     1024
#define IDC_EMISSION_MAP_HEIGHT         1025
#define IDC_EMISSION_MAP_HEIGHT_SPIN    1026
#define IDC_EMISSION_ID                 1027
#define IDC_EMISSION_ID_SPIN            1028
#define IDC_BROWSEFOLDER                1066
#define IDC_DENOISER                    1071
#define IDC_DENOISER_CHECK              1071
#define IDC_AUTOLINEAR                  1072
#define IDC_AUTOLINEAR_CHECK            1072
#define IDC_GAMMA                       1073
#define IDC_VIGNETTING_VALUE            1073
#define IDC_GAMMA_SPIN                  1074
#define IDC_AUTOLINEAR2                 1075
#define IDC_RENDER_TIME_SPIN            1076
#define IDC_RENDER_REFRESH              1077
#define IDC_RENDER_REFRESH_SPIN         1078
#define IDC_RENDER_PASS                 1079
#define IDC_VIGNETTING_TABLE_SIZE       1080
#define IDC_GAUSSIAN_SCALE              1082
#define IDC_GAMMA_TABLESIZE             1084
#define IDC_GAMMA_TABLESIZE_SPIN        1085
#define IDC_GAMMA_CORRECTION_CHECK      1086
#define IDC_LUXLINEAR_CHECK             1087
#define IDC_LUXLINEAR_SENSIVITY         1088
#define IDC_AUTOLINEAR4                 1089
#define IDC_MIST_CHECK                  1089
#define IDC_REINHARD_PRESCALE           1090
#define IDC_REINHARD_PRESCALE_SPIN      1091
#define IDC_MIST_COLOR                  1092
#define IDC_MIST_COLOR_SPIN             1093
#define IDC_MIST_START                  1094
#define IDC_MIST_START_SPIN             1095
#define IDC_CONTOUR_CHECK               1096
#define IDC_LUXLINEAR_SENSIVITY_SPIN    1097
#define IDC_LUXLINEAR_EXPOSURE_SPIN     1098
#define IDC_LUXLINEAR_FSTOP             1099
#define IDC_LUXLINEAR_FSTOP_SPIN        1100
#define IDC_REINHARD_POSTSCALE          1101
#define IDC_REINHARD_POSTSCALE_SPIN     1102
#define IDC_REINHARD_BURN               1103
#define IDC_PATH_DEPTH_SPECULAR         1103
#define IDC_REINHARD_BURN_SPIN          1104
#define IDC_LINEAR_SCALE                1105
#define IDC_LINEAR_SCALE_SPIN           1106
#define IDC_REINHARD_CHECK              1107
#define IDC_LINEAR_CHECK                1108
#define IDC_COLOR_ABERRATION_WEIGHT_SPIN 1109
#define IDC_ENVIRENMENT_MAP             1109
#define IDC_MIST_AMOUNT                 1110
#define IDC_MIST_AMOUNT_SPIN            1111
#define IDC_MIST_BG_CHECK               1114
#define IDC_MIST_END                    1115
#define IDC_MIST_END_SPIN               1116
#define IDC_CONTOUR_GRID_SIZE           1117
#define IDC_CONTOUR_GRID_SIZE_SPIN      1118
#define IDC_GAMMA_VALUE_SPIN            1119
#define IDC_GAUSSIAN_SCALE_SPIN         1120
#define IDC_GAMMA_VALUE                 1122
#define IDC_SYSLINK1                    1123
#define IDC_VIGNETTING_VALUE_SPIN       1174
#define IDC_RENDER_TIME                 1175
#define IDC_VIGNETTING_CHECK            1176
#define IDC_COLOR_ABERRATION_RADIUS     1177
#define IDC_COLOR_ABERRATION_CHECK      1178
#define IDC_COLOR_ABERRATION_RADIUS_SPIN 1179
#define IDC_RENDER_PASS_SPIN            1180
#define IDC_VIGNETTING_TABLE_SIZE_SPIN  1181
#define IDC_RENDER_NOISE_THERESHOLD     1182
#define IDC_DENOISER_SPP_CHECK          1183
#define IDC_GAUSSIAN_CHECK              1184
#define IDC_RENDER_NOISE_THERESHOLD_SPIN 1185
#define IDC_LUXLINEAR_EXPOSURE          1196
#define IDC_CONTOUR_RANGE               1197
#define IDC_CONTOUR_RANGE_SPIN          1198
#define IDC_CONTOUR_SCALE               1199
#define IDC_CONTOUR_SCALE_SPIN          1200
#define IDC_CONTOUR_STEPS               1201
#define IDC_CONTOUR_STEPS_SPIN          1202
#define IDC_BOOM_CHECK                  1203
#define IDC_BLOOM_SENSITIVITY           1204
#define IDC_BLOOM_SENSITIVITY_SPIN      1205
#define IDC_BLOOM_EXPOSURE              1206
#define IDC_BLOOM_EXPOSURE_SPIN         1207
#define IDC_COLOR_ABERRATION_WEIGHT     1208
#define IDC_EMISSION_MAP                1506
#define IDC_EMISSION_MAPFILE            1507
#define IDC_EMISSION_COLOR              1508
#define IDC_EMISSION_IESFILE            1509
#define IDC_EMISSION_FLIPZ              1510
#define IDC_PATH_DEPTH                  1511
#define IDC_PATH_DEPTH_SPIN             1512
#define IDC_PATH_DEPTH_DIFFUSE          1513
#define IDC_PATH_DEPTH_DIFFUSE_SPIN     1514
#define IDC_PATH_DEPTH_GLOSSY           1515
#define IDC_PATH_DEPTH_GLOSSY_SPIN      1516
#define IDC_PATH_RAYS                   1517
#define IDC_PATH_RAYS_SPIN              1518
#define IDC_CLAMPING_CHECK              1519
#define IDC_PATH_DEPTH_SPECULAR_SPIN    1520
#define IDC_PATH_GLOSSY_THRESHOLD_SPIN  1521
#define IDC_PATH_CLAMP_MAX              1522
#define IDC_PATH_CLAMP_MAX_SPIN         1523
#define IDC_LIGHT_TRACING_CHECK         1524
#define IDC_PATH_GLOSSY_THRESHOLD       1525

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
