//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Lux_map.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_CHECKER               3
#define IDS_COORD                       4
#define IDS_COORDS                      4
#define IDS_CLASS_CHECKER3D             5
#define IDS_CHECKER_TEXTURE1_COLOR      6
#define IDS_CHECKER_PARAMS              7
#define IDS_CHECKER_TEXTURE1_MAP        8
#define IDS_CHECKER_TEXTURE2_COLOR      9
#define IDS_CHECKER_TEXTURE2_MAP        10
#define IDS_CHECKER3D_PARAMS            11
#define IDS_CLASS_CHEKER3D              12
#define IDS_CHECKER3D_TEXTURE1_MAP2     13
#define IDS_CHECKER3D_TEXTURE2_COLOR2   14
#define IDS_CHECKER3D_TEXTURE2_MAP2     15
#define IDS_CHECKER_TEXTURE1_COLOR2     16
#define IDS_3DSMAX_SME_MATERIALS_CATLABEL 17
#define IDS_CLASS_VOLUME_CLEAR          17
#define IDS_CLASS_ADD                   18
#define IDS_CLASS_SUBTRACT              19
#define IDS_ADD_PARAMS                  20
#define IDS_SUBTRACT_PARAMS             21
#define IDS_SCALE_PARAMS                22
#define IDS_CLASS_SCALE                 23
#define IDS_CLASS_MIX                   24
#define IDS_MIX_PARAMS                  25
#define IDS_POWER_PARAMS                26
#define IDS_CLASS_POWER                 27
#define IDS_DIVIDE_PARAMS               28
#define IDS_CLASS_DIVIDE                29
#define IDC_VOLUME_HOMO_MULTISCATTERING 29
#define IDS_DOTPRODUCT_PARAMS           30
#define IDS_CLASS_DOTPRODUCT            31
#define IDS_LESSTHAN_PARAMS             32
#define IDS_CLASS_LESSTHAN              33
#define IDS_GREATERTHAN_PARAMS          34
#define IDS_CLASS_GREATERTHAN           35
#define IDS_ABS_PARAMS                  36
#define IDS_CLASS_ABS                   37
#define IDS_CLAMP_PARAMS                38
#define IDS_CLASS_CLAMP                 39
#define IDS_ROUND_PARAMS                40
#define IDS_CLASS_ROUND                 41
#define IDS_MODULO_PARAMS               42
#define IDS_CLASS_MODULO                43
#define IDS_ADD_VALUE_1                 44
#define IDS_ADD_TEXTURE_1               45
#define IDS_ADD_VALUE_2                 46
#define IDS_ADD_TEXTURE_2               47
#define IDS_CLAMP_VALUE                 48
#define IDS_CLAMP_TEXTURE               49
#define IDS_CLAMP_MIN                   50
#define IDS_CLAMP_MAX                   51
#define IDS_MIX_VALUE_1                 52
#define IDS_MIX_TEXTURE_1               53
#define IDS_MIX_VALUE_2                 54
#define IDS_MIX_TEXTURE_2               55
#define IDS_MIX_AMOUNT                  56
#define IDS_SCALE_VALUE_1               57
#define IDS_SCALE_TEXTURE_1             58
#define IDS_SCALE_VALUE_2               59
#define IDS_SCALE_TEXTURE_2             60
#define IDS_MIX_AMOUNT_TEXTURE          61
#define IDS_ABS_VALUE                   62
#define IDS_VOLUME_CLEAR_PARAM          63
#define IDS_ABS_TEXTURE_MAP             64
#define IDS_NORMAL_VALUE                65
#define IDS_NORMAL_TEXTURE_MAP          66
#define IDS_VOLUME_IOR                  67
#define IDS_CLASS_NORMAL                68
#define IDS_NORMAL_PARAMS               69
#define IDS_VOLUME_IOR_MAP              70
#define IDS_VOLUME_ABSORPTION_COLOR     71
#define IDS_VOLUME_ABSORPTION_MAP       72
#define IDS_VOLUME_ABSORPTION_DEPTH     73
#define IDS_VOLUME_EMISSION_COLOR       74
#define IDS_VOLUME_EMISSION_MAP         75
#define IDS_VOLUME_PRIORITY             76
#define IDS_VOLUME_ID                   77
#define IDS_VOLUME_HETRO_STEPSIZE       78
#define IDS_VOLUME_HETRO_MAX_STEP       79
#define IDS_VOLUME_HETRO_PRIORITY       80
#define IDS_VOLUME_HETRO_AUTO_STEP      81
#define IDS_VOLUME_HOMO_SCATTERING_COLOR 82
#define IDS_VOLUME_HOMO_SCATTERING_MAP  83
#define IDS_VOLUME_HOMO_SCATTERING_SCALE 84
#define IDS_VOLUME_HOMO_ASYMMETRY_COLOR 85
#define IDS_VOLUME_HOMO_ASYMMETRY_MAP   86
#define IDS_VOLUME_HOMO_MULTISCATTERING 87
#define IDS_CLASS_VOLUME_HOMO           88
#define IDS_CLASS_VOLUME_HETRO          89
#define IDS_VOLUME_HOMO_PARAM           90
#define IDS_VOLUME_HETRO_PARAM          91
#define IDD_CHECKER_PANEL               101
#define IDD_CHECKER3D_PANEL             102
#define IDD_ADD_PANEL                   103
#define IDD_CHECKER_PANEL2              104
#define IDD_SUBTRACT_PANEL              104
#define IDD_SCALE_PANEL                 105
#define IDD_MIX_PANEL                   106
#define IDD_POWER_PANEL                 107
#define IDD_DIVIDE_PANEL                108
#define IDD_DOTPRODUCT_PANEL            109
#define IDD_LESSTHAN_PANEL              110
#define IDD_GREATERTHAN_PANEL           111
#define IDD_ABS_PANEL                   112
#define IDD_CLAMP_PANEL                 113
#define IDD_ROUND_PANEL                 114
#define IDD_MODULO_PANEL                115
#define IDD_NORMAL_PANEL                116
#define IDD_VOLUME_COMMON_PANEL         117
#define IDD_VOLUME_HOMOGENEOUS_PANEL    118
#define IDD_VOLUME_HETEROGENEUS_PANEL   119
#define IDD_VOLUME_HETEROGENEOUS_PANEL  119
#define IDC_CLOSEBUTTON                 1000
#define IDC_CHECKER3D_TEXTURE1_COLOR    1001
#define IDC_CHECKER3D_TEXTURE1_MAP      1002
#define IDC_CHECKER3D_TEXTURE2_COLOR    1003
#define IDC_CHECKER3D_TEXTURE2_MAP      1004
#define IDC_CHECKER_TEXTURE1_COLOR      1005
#define IDC_SCALE_VALUE_1               1005
#define IDC_CHECKER_TEXTURE1_MAP        1006
#define IDC_VOLUME_EMISSION_COLOR       1006
#define IDC_CHECKER_TEXTURE2_COLOR      1007
#define IDC_SCALE_VALUE_1_SPIN          1007
#define IDC_CHECKER_TEXTURE2_MAP        1008
#define IDC_SCALE_VALUE_2               1009
#define IDC_SCALE_VALUE_2_SPIN          1010
#define IDC_SUBTRACT_VALUE_1            1011
#define IDC_SUBTRACT_VALUE_1_SPIN       1012
#define IDC_SUBTRACT_VALUE_2            1013
#define IDC_SUBTRACT_VALUE_2_SPIN       1014
#define IDC_MIX_VALUE_1                 1015
#define IDC_MIX_VALUE_1_SPIN            1016
#define IDC_MIX_VALUE_2                 1017
#define IDC_MIX_VALUE_2_SPIN            1018
#define IDC_ADD_VALUE_1                 1019
#define IDC_ADD_VALUE_1_SPIN            1020
#define IDC_ADD_VALUE_2                 1021
#define IDC_ADD_VALUE_2_SPIN            1022
#define IDC_MIX_VALUE                   1023
#define IDC_MIX_AMOUNT                  1023
#define IDC_CLAMP_MAX                   1023
#define IDC_ADD_TEXTURE_2_MAP           1023
#define IDC_ADD_VALUE_2_SPIN2           1024
#define IDC_CLAMP_MAX_SPIN              1024
#define IDC_ADD_TEXTURE_1_MAP           1024
#define IDC_MIX_AMOUNT_SPIN             1024
#define IDC_MIX_TEXTURE_1               1025
#define IDC_MIX_TEXTURE_2               1026
#define IDC_SCALE_TEXTURE_1             1027
#define IDC_MIX_AMOUNT_TEXTURE          1027
#define IDC_SCALE_TEXTURE_2             1028
#define IDC_VOLUME_ID                   1028
#define IDC_SUBTRACT_TEXTURE1_MAP       1029
#define IDC_VOLUME_ID_SPIN              1029
#define IDC_SUBTRACT_TEXTURE2_MAP       1030
#define IDC_POWER_VALUE_1               1031
#define IDC_POWER_VALUE_1_SPIN          1032
#define IDC_POWER_VALUE_2               1033
#define IDC_POWER_VALUE_2_SPIN          1034
#define IDC_POWER_TEXTURE1_MAP          1035
#define IDC_POWER_TEXTURE2_MAP          1036
#define IDC_DIVIDE_VALUE_1              1037
#define IDC_DIVIDE_VALUE_1_SPIN         1038
#define IDC_DIVIDE_TEXTURE1_MAP         1039
#define IDC_DIVIDE_VALUE_2              1040
#define IDC_DIVIDE_VALUE_2_SPIN         1041
#define IDC_DIVIDE_TEXTURE2_MAP         1042
#define IDC_DOTPRODUCT_VALUE_1          1043
#define IDC_DOTPRODUCT_VALUE_1_SPIN     1044
#define IDC_DOTPRODUCT_TEXTURE1_MAP     1045
#define IDC_DOTPRODUCT_VALUE_2          1046
#define IDC_DOTPRODUCT_VALUE_2_SPIN     1047
#define IDC_DOTPRODUCT_TEXTURE2_MAP     1048
#define IDC_LESSTHAN_VALUE_1            1049
#define IDC_LESSTHAN_VALUE_1_SPIN       1050
#define IDC_LESSTHAN_TEXTURE1_MAP       1051
#define IDC_LESSTHAN_VALUE_2            1052
#define IDC_LESSTHAN_VALUE_2_SPIN       1053
#define IDC_LESSTHAN_TEXTURE2_MAP       1054
#define IDC_GREATERTHAN_VALUE_1         1055
#define IDC_GREATERTHAN_VALUE_1_SPIN    1056
#define IDC_GREATERTHAN_TEXTURE1_MAP    1057
#define IDC_GREATERTHAN_VALUE_2         1058
#define IDC_GREATERTHAN_VALUE_2_SPIN    1059
#define IDC_GREATERTHAN_TEXTURE2_MAP    1060
#define IDC_ABS_VALUE                   1061
#define IDC_ABS_VALUE_SPIN              1062
#define IDC_ABS_TEXTURE_MAP             1063
#define IDC_CLAMP_VALUE                 1064
#define IDC_CLAMP_VALUE_SPIN            1065
#define IDC_CLAMP_TEXTURE               1066
#define IDC_CLAMP_MIN                   1067
#define IDC_CLAMP_MIN_SPIN              1068
#define IDC_ROUND_VALUE_1               1069
#define IDC_ROUND_VALUE_1_SPIN          1070
#define IDC_ROUND_TEXTURE1_MAP          1071
#define IDC_ROUND_VALUE_2               1072
#define IDC_ROUND_VALUE_2_SPIN          1073
#define IDC_ROUND_TEXTURE2_MAP          1074
#define IDC_MODULO_VALUE_1              1075
#define IDC_MODULO_VALUE_1_SPIN         1076
#define IDC_MODULO_TEXTURE1_MAP         1077
#define IDC_MODULO_VALUE_2              1078
#define IDC_MODULO_VALUE_2_SPIN         1079
#define IDC_MODULO_TEXTURE2_MAP         1080
#define IDC_NORMAL_VALUE                1081
#define IDC_NORMAL_VALUE_SPIN           1082
#define IDC_NORMAL_TEXTURE_MAP          1083
#define IDC_VOLUME_IOR                  1084
#define IDC_VOLUME_IOR_SPIN             1085
#define IDC_VOLUME_IOR_MAP              1086
#define IDC_VOLUME_ABSORPTION_COLOR     1087
#define IDC_VOLUME_ABSORPTION_MAP       1088
#define IDC_VOLUME_ABSORPTION_DEPTH     1089
#define IDC_VOLUME_ABSORPTION_DEPTH_SPIN 1090
#define IDC_VOLUME_EMISSION_MAP         1091
#define IDC_VOLUME_HETRO_MAX_STEP       1091
#define IDC_VOLUME_PRIORITY             1092
#define IDC_VOLUME_HETRO_MAX_STEP_SPIN  1092
#define IDC_VOLUME_PRIORITY_SPIN        1093
#define IDC_VOLUME_HETRO_PRIORITY       1093
#define IDC_VOLUME_HETRO_PRIORITY_SPIN  1094
#define IDC_VOLUME_HETRO_STEPSIZE       1095
#define IDC_VOLUME_HETRO_STEPSIZE_SPIN  1096
#define IDC_VOLUME_HETRO_AUTO_STEP      1097
#define IDC_VOLUME_HOMO_SCATTERING_COLOR 1098
#define IDC_VOLUME_HOMO_SCATTERING_MAP  1099
#define IDC_VOLUME_HOMO_SCATTERING_SCALE 1100
#define IDC_VOLUME_HOMO_SCATTERING_SCALE_SPIN 1101
#define IDC_VOLUME_HOMO_ASYMMETRY_COLOR 1102
#define IDC_VOLUME_HOMO_ASYMMETRY_MAP   1103
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
