//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RenderingAPI.rc
//
#define IDS_ENVIRONMENT_CONTAINER_PB_NAME 17
#define IDS_ENVIRONMENT_CONTAINER_PARAM_BACKGROUNDMODE 20
#define IDS_LOG_RENDERER_PAUSED         78
#define IDS_LOG_RENDERER_UNPAUSED       79
#define IDS_ERROR_CREATION_INTERACTIVE_SESSION 80
#define IDS_ERROR_UPDATING_SCENE        81
#define IDS_PROCESSING_RENDER_ELEMENTS  82
#define IDS_RENDER_ELEMENTS_PROCESSED   83
#define IDS_ERROR_RENDER_ELEMENTS       84
#define IDS_TIMING_TABLE_HEADER         85
#define IDS_TIMING_MISC_TRANSLATION     86
#define IDS_TIMING_TOTAL_TRANSLATION    87
#define IDS_TIMING_TRANSLATION_PREFIX   88
#define IDS_TIMING_CAMERA               89
#define IDS_TIMING_ENVIRONMENT          90
#define IDS_TIMING_MTLBASE              91
#define IDS_SESSION_CREATION            92
#define IDS_SESSION_DESTRUCTION         93
#define IDS_ENVIRONMENT_CONTAINER_PARAM_BACKGROUNDCOLOR 94
#define IDS_ENVIRONMENT_CONTAINER_PARAM_BACKGROUNDTEXTURE 95
#define IDS_ENVIRONMENT_CONTAINER_PARAM_ENVCOLOR 96
#define IDS_ENVIRONMENT_CONTAINER_PARAM_ENVMODE 97
#define IDS_RENDERER_PLUGIN_CATEGORY    101
#define IDS_PROGRESS_INITIAL_TITLE      102
#define IDS_LOG_SCENE_TRANSLATION_TIME  103
#define IDS_SCENE_UPDATE_TIME           104
#define IDS_ERROR_RENDER_SESSION_CREATION 104
#define IDS_LOG_RENDER_TIME             105
#define IDS_LOG_FIRST_BITMAP_UPDATE_TIME 106
#define IDS_LOG_TRANSLATING             107
#define IDS_LOG_RENDERING               108
#define IDS_RENDERING_FAILED            109
#define IDS_TRANSLATION_FAILED          110
#define IDS_ENVIRONMENT_CONTAINER_CLASSNAME 111
#define IDS_ENVIRONMENT_CONTAINER_PARAM_ENVTEXTURE 112
#define IDS_ERROR_ACQUIREWHILEKEYFRAME  120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
